"""Fix typo

Revision ID: 0953d8302f4e
Revises: a458682bd01f
Create Date: 2023-11-08 02:33:50.201401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0953d8302f4e'
down_revision = 'a458682bd01f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=False))
        batch_op.drop_column('logitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logitude', sa.FLOAT(), nullable=False))
        batch_op.drop_column('longitude')

    # ### end Alembic commands ###
