"""Add multimedia type

Revision ID: 37428f2247bc
Revises: 9959fed5e64f
Create Date: 2023-10-22 17:59:38.628636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37428f2247bc'
down_revision = '9959fed5e64f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multimedia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multimedia', schema=None) as batch_op:
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
