"""empty message

Revision ID: a458682bd01f
Revises: 86143f568fae
Create Date: 2023-11-08 02:00:27.170343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a458682bd01f'
down_revision = '86143f568fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('logitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('radius', sa.Float(), nullable=False))
        batch_op.drop_column('north_boundary')
        batch_op.drop_column('south_boundary')
        batch_op.drop_column('west_boundary')
        batch_op.drop_column('east_boundary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('east_boundary', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('west_boundary', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('south_boundary', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('north_boundary', sa.FLOAT(), nullable=False))
        batch_op.drop_column('radius')
        batch_op.drop_column('logitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
